Repository philippemerle/KubeDiagrams, pull requests merged in 2025-04, with the labels that each got.

#24 chore: add direnv support
  .envrc
  .gitignore
  flake.lock
  flake.nix
Labels: documentation, enhancement, good first issue

#26 chore: update flake for packaging
  CONTRIBUTING.md
  flake.lock
  flake.nix
Labels: enhancement

#32 build : Add multiarch (arm) to docker image build
  .github/workflows/docker-image.yml
Labels: enhancement, good first issue
